# Site settings
title: Jirawat Boonkumnerd
# generate header img from https://www.svgbackgrounds.com/
header-img: data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 2000 1500'%3E%3Cdefs%3E%3Crect stroke='%23000000' stroke-width='0.12' width='1' height='1' id='s'/%3E%3Cpattern id='a' width='3' height='3' patternUnits='userSpaceOnUse' patternTransform='scale(42.85) translate(-976.66 -732.5)'%3E%3Cuse fill='%23050505' href='%23s' y='2'/%3E%3Cuse fill='%23050505' href='%23s' x='1' y='2'/%3E%3Cuse fill='%230a0a0a' href='%23s' x='2' y='2'/%3E%3Cuse fill='%230a0a0a' href='%23s'/%3E%3Cuse fill='%230f0f0f' href='%23s' x='2'/%3E%3Cuse fill='%230f0f0f' href='%23s' x='1' y='1'/%3E%3C/pattern%3E%3Cpattern id='b' width='7' height='11' patternUnits='userSpaceOnUse' patternTransform='scale(42.85) translate(-976.66 -732.5)'%3E%3Cg fill='%23141414'%3E%3Cuse href='%23s'/%3E%3Cuse href='%23s' y='5' /%3E%3Cuse href='%23s' x='1' y='10'/%3E%3Cuse href='%23s' x='2' y='1'/%3E%3Cuse href='%23s' x='2' y='4'/%3E%3Cuse href='%23s' x='3' y='8'/%3E%3Cuse href='%23s' x='4' y='3'/%3E%3Cuse href='%23s' x='4' y='7'/%3E%3Cuse href='%23s' x='5' y='2'/%3E%3Cuse href='%23s' x='5' y='6'/%3E%3Cuse href='%23s' x='6' y='9'/%3E%3C/g%3E%3C/pattern%3E%3Cpattern id='h' width='5' height='13' patternUnits='userSpaceOnUse' patternTransform='scale(42.85) translate(-976.66 -732.5)'%3E%3Cg fill='%23141414'%3E%3Cuse href='%23s' y='5'/%3E%3Cuse href='%23s' y='8'/%3E%3Cuse href='%23s' x='1' y='1'/%3E%3Cuse href='%23s' x='1' y='9'/%3E%3Cuse href='%23s' x='1' y='12'/%3E%3Cuse href='%23s' x='2'/%3E%3Cuse href='%23s' x='2' y='4'/%3E%3Cuse href='%23s' x='3' y='2'/%3E%3Cuse href='%23s' x='3' y='6'/%3E%3Cuse href='%23s' x='3' y='11'/%3E%3Cuse href='%23s' x='4' y='3'/%3E%3Cuse href='%23s' x='4' y='7'/%3E%3Cuse href='%23s' x='4' y='10'/%3E%3C/g%3E%3C/pattern%3E%3Cpattern id='c' width='17' height='13' patternUnits='userSpaceOnUse' patternTransform='scale(42.85) translate(-976.66 -732.5)'%3E%3Cg fill='%231a1a1a'%3E%3Cuse href='%23s' y='11'/%3E%3Cuse href='%23s' x='2' y='9'/%3E%3Cuse href='%23s' x='5' y='12'/%3E%3Cuse href='%23s' x='9' y='4'/%3E%3Cuse href='%23s' x='12' y='1'/%3E%3Cuse href='%23s' x='16' y='6'/%3E%3C/g%3E%3C/pattern%3E%3Cpattern id='d' width='19' height='17' patternUnits='userSpaceOnUse' patternTransform='scale(42.85) translate(-976.66 -732.5)'%3E%3Cg fill='%23000000'%3E%3Cuse href='%23s' y='9'/%3E%3Cuse href='%23s' x='16' y='5'/%3E%3Cuse href='%23s' x='14' y='2'/%3E%3Cuse href='%23s' x='11' y='11'/%3E%3Cuse href='%23s' x='6' y='14'/%3E%3C/g%3E%3Cg fill='%231f1f1f'%3E%3Cuse href='%23s' x='3' y='13'/%3E%3Cuse href='%23s' x='9' y='7'/%3E%3Cuse href='%23s' x='13' y='10'/%3E%3Cuse href='%23s' x='15' y='4'/%3E%3Cuse href='%23s' x='18' y='1'/%3E%3C/g%3E%3C/pattern%3E%3Cpattern id='e' width='47' height='53' patternUnits='userSpaceOnUse' patternTransform='scale(42.85) translate(-976.66 -732.5)'%3E%3Cg fill='%230f0c0c'%3E%3Cuse href='%23s' x='2' y='5'/%3E%3Cuse href='%23s' x='16' y='38'/%3E%3Cuse href='%23s' x='46' y='42'/%3E%3Cuse href='%23s' x='29' y='20'/%3E%3C/g%3E%3C/pattern%3E%3Cpattern id='f' width='59' height='71' patternUnits='userSpaceOnUse' patternTransform='scale(42.85) translate(-976.66 -732.5)'%3E%3Cg fill='%230f0c0c'%3E%3Cuse href='%23s' x='33' y='13'/%3E%3Cuse href='%23s' x='27' y='54'/%3E%3Cuse href='%23s' x='55' y='55'/%3E%3C/g%3E%3C/pattern%3E%3Cpattern id='g' width='139' height='97' patternUnits='userSpaceOnUse' patternTransform='scale(42.85) translate(-976.66 -732.5)'%3E%3Cg fill='%230f0c0c'%3E%3Cuse href='%23s' x='11' y='8'/%3E%3Cuse href='%23s' x='51' y='13'/%3E%3Cuse href='%23s' x='17' y='73'/%3E%3Cuse href='%23s' x='99' y='57'/%3E%3C/g%3E%3C/pattern%3E%3C/defs%3E%3Crect fill='url(%23a)' width='100%25' height='100%25'/%3E%3Crect fill='url(%23b)' width='100%25' height='100%25'/%3E%3Crect fill='url(%23h)' width='100%25' height='100%25'/%3E%3Crect fill='url(%23c)' width='100%25' height='100%25'/%3E%3Crect fill='url(%23d)' width='100%25' height='100%25'/%3E%3Crect fill='url(%23e)' width='100%25' height='100%25'/%3E%3Crect fill='url(%23f)' width='100%25' height='100%25'/%3E%3Crect fill='url(%23g)' width='100%25' height='100%25'/%3E%3C/svg%3E
email: contact@ntsd.dev
description: "A software engineer who loves coding."
keyword: "Programming, Web Development, Coding, Artificial Intelligence, Machine Learning, Jirawat Boonkumnerd"
url: "https://ntsd.dev" # host for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Gems
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-lazy-load-image
  - jekyll-feed

# Build settings
permalink: /:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml

# Pagination Settings https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#page-configuration
pagination:
  enabled: true
  per_page: 7
  sort_reverse: true
  permalink: "/page/:num/"
  title: ":title"
  trail:
    before: 2 # The number of links before the current page
    after: 2 # The number of links after the current page

anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
future: true # Publish posts or collection documents with a future date.

# RSS
feed:
  posts_limit: 20

# SNS settings
RSS: true
github_username: ntsd
# twitter_username: ntsd_me
# facebook_username: jo.ntsd
linkedin_username: ntsd
# github_btn: ntsd.github.io # Github repository name

# Config compress html https://jch.penibelst.de/
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]

# Lazyload all images https://github.com/kenchan0130/jekyll-lazy-load-image
lazy_load_image:
  src_attr_name: src
  additional_attrs:
    "loading": "lazy"

# Seo Tag setting https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
defaults:
  - scope:
      path: ""
    values:
      image: /pwa/icons/512.png # can't use svg
logo: /pwa/icons/icon-min.svg
# twitter:
#   username: ntsd_me
#   card: summary
facebook:
  app_id: 1034059654428260
social:
  name: Jirawat Boonkumnerd
  links:
    - https://github.com/ntsd
    - https://www.linkedin.com/in/ntsd
    - https://facebook.com/ntsd.dev

# Markdown settings http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important

prism: true

# Giscus
giscus: true

# Google Analytics
# ga_track_id: 'G-XGQGF8LG4L' # Format: UA-xxxxxx-xx
# ga_domain: ntsd.dev

# Sidebar settings
sidebar-about-description: '<div class="font-bond text-xl">Jirawat Boonkumnerd</div> A Software Engineer'
# sidebar-avatar: /img/me.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 0 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Projects
projects:
  - zero-share:
    name: Zero Share
    description: A client-side secure P2P file sharing using WebRTC.
    date: 2023 - present
    github: https://github.com/ntsd/zero-share
    web: https://zero-share.github.io
    stacks: [Svelte , TypeScript, WebRTC]
  - auto-evm-wallet:
    name: Auto EVM Wallet
    description: EVM wallet that allow to schedule or automate smart contract call.
    date: 2023 - present
    github: https://github.com/ntsd/auto-evm-wallet
    web: https://ntsd.github.io/auto-evm-wallet
    stacks: [Svelte , TypeScript, Web3.js]
  - sdp-compress:
    name: SDP Compact
    description: Shorten WebRTC Session Description Protocol (SDP) based on Unified Plan SDP.
    date: 2023 - present
    github: https://github.com/ntsd/sdp-compact
    web: https://ntsd.github.io/sdp-compact
    npm: https://www.npmjs.com/package/sdp-compact
    stacks: [TypeScript]
  - cross-clipboard:
    name: Cross Clipboard
    description: An open source cross-platform clipboard sharing.
    date: 2022 - present
    github: https://github.com/ntsd/cross-clipboard
    stacks: [Go, LibP2P]
  - freqtrade-configs:
    name: Freqtrade Configs
    description: My Freqtrade strategies and config.
    date: 2022
    github: https://github.com/ntsd/freqtrade-configs
    stacks: [Python]
  - ntsd.dev:
    name: ntsd.dev
    description: My website created by Jekyll and Tailwind.
    date: 2020 - present
    github: https://github.com/ntsd/ntsd.dev
    web: https://ntsd.dev
    stacks: [Jekyll, JavaScript, Gulp]
  - github-profile-repositories:
    name: Github Profile Repositories
    description: Automatically create repositories list for your Github Profile.
    date: 2022
    github: https://github.com/ntsd/github-profile-repositories
    web: https://github.com/marketplace/actions/github-profile-repositories
    stacks: [TypeScript, Github Action]
  - liquidjs-action:
    name: LiquidJS Github Action
    description: Github Action to render LiquidJS.
    date: 2022
    github: https://github.com/ntsd/liquidjs-action
    web: https://github.com/marketplace/actions/liquidjs-render
    stacks: [TypeScript, Github Action]
  - auto-request-changes-action:
    name: Auto Request Changes GitHub Action
    description: GitHub Action for automatically request changes GitHub pull requests.
    date: 2022
    github: https://github.com/ntsd/auto-request-changes-action
    web: https://github.com/marketplace/actions/auto-request-changes
    stacks: [TypeScript, Github Action]
  - binance-auto-limit-price:
    name: Binance Auto Limit Price
    description: A Binance extension to auto change limit price to the best ask/bid orders.
    date: 2021
    github: https://github.com/ntsd/binance-auto-limit-price
    stacks: [JavaScript]
  - threejs-merry-christmas:
    name: Three.js Merry Christmas
    description: 3D Christmas Theme by Three.js.
    date: 2021
    github: https://github.com/ntsd/threejs-merry-christmas
    web: https://ntsd.github.io/threejs-merry-christmas
    stacks: [JavaScript, Three.js]
  - google-sheet-import-cache:
    name: Google Sheet Import Cache
    description: A Google Sheet custom function add-on used for web scraping and supporting cache created by Google Apps Script.
    date: 2021
    github: https://github.com/ntsd/google-sheet-import-cache
    stacks: [Google Apps Script]
  - ruamrat:
    name: Ruamrat Website
    description: Website for Ruamrat Aluminium Glass Business.
    date: 2019
    github: https://github.com/ntsd/ruamrat
    web: https://ruamrat.com
    stacks: [TypeScript, React, Gatsby]

# About
about:
  intro: I am Jirawat Boonkumnerd (Jo), A Software Engineer from Thailand who loves programming and problem-solving. I always learning new things every day.
